---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8000'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
    - 8000:8000
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      #Change this with the right path
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'pyris'
      LIMIT_RESOURCES: 'true'
      DISK_USE_WARNING_PERCENTAGE: '80'
      vectorCacheMaxObjects: '1000000'
      #GOMAXPROCS: you can set the number of threads that can be used by Weaviate
volumes:
  weaviate_data:
...
