---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8001'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
      - 8001:8001
      - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:3
    env_file:
      - ./weaviate/default.env  # Changed to a relative path
volumes:
  weaviate_data:
...
